### ISSUE TITLE
Execption on data download

### ISSUE THREAD

**Issue by AirVan21** [AirVan21/EasyStocks#4]
`
[2020-03-09 14:54:33,594: ERROR/ForkPoolWorker-1] Task stocks.tasks.download_and_draw_share[41679157-74ca-47c0-b7e6-99eaa741be71] raised unexpected: TypeError('Invalid comparison between dtype=datetime64[ns] and date')
Traceback (most recent call last):
  File "/Users/ivan.abramov/.local/share/virtualenvs/EasyStocks-Y6gAEsoh/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/ivan.abramov/.local/share/virtualenvs/EasyStocks-Y6gAEsoh/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/ivan.abramov/GitHub/EasyStocks/stocks/tasks.py", line 27, in download_and_draw_share
    data_item_loader.load_update()
  File "/Users/ivan.abramov/GitHub/EasyStocks/shared/share_data_item_loader.py", line 39, in load_update
    csv_update = csv_file[csv_file['timestamp'] > last_data_item.date]
  File "/Users/ivan.abramov/.local/share/virtualenvs/EasyStocks-Y6gAEsoh/lib/python3.7/site-packages/pandas/core/ops/common.py", line 64, in new_method
    return method(self, other)
  File "/Users/ivan.abramov/.local/share/virtualenvs/EasyStocks-Y6gAEsoh/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 526, in wrapper
    res_values = comparison_op(lvalues, rvalues, op)
  File "/Users/ivan.abramov/.local/share/virtualenvs/EasyStocks-Y6gAEsoh/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 237, in comparison_op
    res_values = dispatch_to_extension_op(op, lvalues, rvalues)
  File "/Users/ivan.abramov/.local/share/virtualenvs/EasyStocks-Y6gAEsoh/lib/python3.7/site-packages/pandas/core/ops/dispatch.py", line 125, in dispatch_to_extension_op
    res_values = op(left, right)
  File "/Users/ivan.abramov/.local/share/virtualenvs/EasyStocks-Y6gAEsoh/lib/python3.7/site-packages/pandas/core/ops/common.py", line 64, in new_method
    return method(self, other)
  File "/Users/ivan.abramov/.local/share/virtualenvs/EasyStocks-Y6gAEsoh/lib/python3.7/site-packages/pandas/core/arrays/datetimelike.py", line 83, in wrapper
    return invalid_comparison(self, other, op)
  File "/Users/ivan.abramov/.local/share/virtualenvs/EasyStocks-Y6gAEsoh/lib/python3.7/site-packages/pandas/core/ops/invalid.py", line 34, in invalid_comparison
    raise TypeError(f"Invalid comparison between dtype={left.dtype} and {typ}")
TypeError: Invalid comparison between dtype=datetime64[ns] and date
[2020-03-09 14:54:33,603: INFO/ForkPoolWorker-1] stocks.tasks.downlo
`

**Comment by AirVan21** [comment]
Fixed in [commit](https://github.com/AirVan21/EasyStocks/commit/cfa0b0e6c94cba39209c650c9b155664aa132ef2)
