### ISSUE TITLE
Exception on empty csv file from MDP

### ISSUE THREAD

**Issue by AirVan21** [AirVan21/EasyStocks#7]
Trace:
`
[2020-08-10 18:48:57,227: ERROR/ForkPoolWorker-1] Task stocks.tasks.download_and_draw_share[243b3da7-4719-4601-bf67-814371d82d68] raised unexpected: KeyError('timestamp')
Traceback (most recent call last):
  File "/Users/ivan.abramov/.local/share/virtualenvs/EasyStocks-Y6gAEsoh/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'timestamp'
`

**Comment by AirVan21** [comment]
The problem should be fixed in 72c9360.
